/* eslint-disable max-lines */

import { FileItem } from "@/types/data";

export const esBaseData: FileItem[] = [
  {
    id: 71381,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "העתק אור עקיבא",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/העתק אור עקיבא.docs"
  },
  {
    id: 49732,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיפוי העתקים בברניקי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מיפוי העתקים בברניקי.docs"
  },
  {
    id: 84050,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עדכון מעמד העתקים 2018",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עדכון מעמד העתקים 2018.docs"
  },
  {
    id: 71043,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עדכון מעמד העתקים 2022",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עדכון מעמד העתקים 2022.docs"
  },
  {
    id: 28924,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "פעילות טקטונית כרמל ונשר",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פעילות טקטונית כרמל ונשר.docs"
  },
  {
    id: 85806,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "רכס חוסם צפוני בכרמל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/רכס חוסם צפוני בכרמל.docs"
  },
  {
    id: 84518,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "קריעת פני שטח בטבריה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/קריעת פני שטח בטבריה.docs"
  },
  {
    id: 43221,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "העתק אחיהוד",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/העתק אחיהוד.docs"
  },
  {
    id: 54062,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיקום העתק הכרמל מניתוח תתקרקע",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מיקום העתק הכרמל מניתוח תתקרקע.docs"
  },
  {
    id: 20531,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מדידות רעש לאיתור העתק הכרמל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדידות רעש לאיתור העתק הכרמל.docs"
  },
  {
    id: 28385,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מפת סיכון ארצית להעתקה פעילה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מפת סיכון ארצית להעתקה פעילה.docs"
  },
  {
    id: 86975,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "העתקים פעילים אילת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/העתקים פעילים אילת.docs"
  },
  {
    id: 43725,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מבנה תלת מימדי למפרץ אילת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מבנה תלת מימדי למפרץ אילת.docs"
  },
  {
    id: 51378,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "זמני חזרה של רעידות בכנרת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/זמני חזרה של רעידות בכנרת.docs"
  },
  {
    id: 28515,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "העתקים במדרון היבשת וטקטוניקת מלח",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/העתקים במדרון היבשת וטקטוניקת מלח.docs"
  },
  {
    id: 33624,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אפיון העתקים במדרון היבשת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אפיון העתקים במדרון היבשת.docs"
  },
  {
    id: 44497,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הגברת תנודות בעמק זבולון א",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הגברת תנודות בעמק זבולון א.docs"
  },
  {
    id: 73230,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הגברת תנודות בשפלה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הגברת תנודות בשפלה.docs"
  },
  {
    id: 38837,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הגברת תנודות בעמק זבולון ב",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הגברת תנודות בעמק זבולון ב.docs"
  },
  {
    id: 44504,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "היחס בין שטח וגודל גלישות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/היחס בין שטח וגודל גלישות.docs"
  },
  {
    id: 47412,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גלישות אזור אילת אילות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/גלישות אזור אילת אילות.docs"
  },
  {
    id: 63280,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גלישות באזור בית שאן",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/גלישות באזור בית שאן.docs"
  },
  {
    id: 93247,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סיכון נפילת סלעים חפציבה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סיכון נפילת סלעים חפציבה.docs"
  },
  {
    id: 47576,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "טיפוסי כשל מדרון בחיפה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/טיפוסי כשל מדרון בחיפה.docs"
  },
  {
    id: 71124,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מפת סכנה ארצית לגלישות צפון",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מפת סכנה ארצית לגלישות צפון.docs"
  },
  {
    id: 60785,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מפת סכנה ארצית לגלישות דרום",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מפת סכנה ארצית לגלישות דרום.docs"
  },
  {
    id: 18944,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "גלישות תת ימיות במדרון היבשת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/גלישות תת ימיות במדרון היבשת.docs"
  },
  {
    id: 30862,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אלגוריתם לחיזוי גלישת קרקע",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אלגוריתם לחיזוי גלישת קרקע.docs"
  },
  {
    id: 77482,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנזלות בבית שאן",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/התנזלות בבית שאן.docs"
  },
  {
    id: 32438,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנזלות בעמק זבולון",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/התנזלות בעמק זבולון.docs"
  },
  {
    id: 15452,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנזלות אילת אילות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/התנזלות אילת אילות.docs"
  },
  {
    id: 29079,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הערכה גיאוטכנית להתנזלות בזבולון",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הערכה גיאוטכנית להתנזלות בזבולון.docs"
  },
  {
    id: 47840,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הערכת מיקום ועוצמה מלווינים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הערכת מיקום ועוצמה מלווינים.docs"
  },
  {
    id: 34429,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "שאלון עדכני לקביעת עוצמות סייסמיות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/שאלון עדכני לקביעת עוצמות סייסמיות.docs"
  },
  {
    id: 30047,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אימוץ סולם עוצמה אירופאי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אימוץ סולם עוצמה אירופאי.docs"
  },
  {
    id: 87285,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "סימולציה לצונמי בים המלח",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סימולציה לצונמי בים המלח.docs"
  },
  {
    id: 64444,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מודל סיכון לצונמי בת גלים ואילת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מודל סיכון לצונמי בת גלים ואילת.docs"
  },
  {
    id: 57478,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הדמיית תרחישי צונמי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הדמיית תרחישי צונמי.docs"
  },
  {
    id: 71996,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סף מגניטודה לצונמי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סף מגניטודה לצונמי.docs"
  },
  {
    id: 71977,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פגיעת צונמי בתשתיות ימיות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פגיעת צונמי בתשתיות ימיות.docs"
  },
  {
    id: 17214,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "ניתוח היסטורי סכנה לצונמי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/ניתוח היסטורי סכנה לצונמי.docs"
  },
  {
    id: 30476,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סיכום סיכונים בחיפה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סיכום סיכונים בחיפה.docs"
  },
  {
    id: 31251,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סיכונים והעתקים בבקעת הירדן",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סיכונים והעתקים בבקעת הירדן.docs"
  },
  {
    id: 52391,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיפוי סיכונים אזור מתלול צורים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מיפוי סיכונים אזור מתלול צורים.docs"
  },
  {
    id: 79389,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "בסיס נתונים גאודטי עבור הדרום",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/בסיס נתונים גאודטי עבור הדרום.docs"
  },
  {
    id: 66857,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מיפוי סיכונים והעתקים בבית שאן",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מיפוי סיכונים והעתקים בבית שאן.docs"
  },
  {
    id: 46514,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הסיכון לרעידת אדמה בטבריה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הסיכון לרעידת אדמה בטבריה.docs"
  },
  {
    id: 13579,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תכנת ורוניק",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תכנת ורוניק.docs"
  },
  {
    id: 68266,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "אפיון תופעות סביבה מרעידות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אפיון תופעות סביבה מרעידות.docs"
  },
  {
    id: 44293,
    category: "ועדת ההיגוי",
    subCategory: "plans ותפיסות לאומיות",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תפיסה לאומית לרעידת אדמה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תפיסה לאומית לרעידת אדמה.docs"
  },
  {
    id: 51490,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פוסטר הנחיות במשטרה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פוסטר הנחיות במשטרה.docs"
  },
  {
    id: 14328,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פוסטר הנחיות בבתי חולים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פוסטר הנחיות בבתי חולים.docs"
  },
  {
    id: 41626,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "russian",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה רוסית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון היערכות לרעידות אדמה רוסית.docs"
  },
  {
    id: 49563,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה ערבית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון היערכות לרעידות אדמה ערבית.docs"
  },
  {
    id: 52536,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "english",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה אנגלית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון היערכות לרעידות אדמה אנגלית.docs"
  },
  {
    id: 45444,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עלון היערכות לרעידות אדמה עברית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון היערכות לרעידות אדמה עברית.docs"
  },
  {
    id: 80743,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה עברית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הנחיות ברעידת אדמה עברית.docs"
  },
  {
    id: 71214,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה ערבית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הנחיות ברעידת אדמה ערבית.docs"
  },
  {
    id: 53736,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "russian",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה רוסית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הנחיות ברעידת אדמה רוסית.docs"
  },
  {
    id: 29684,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הנחיות ברעידת אדמה אנגלית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הנחיות ברעידת אדמה אנגלית.docs"
  },
  {
    id: 75622,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מצגת הסברה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מצגת הסברה.docs"
  },
  {
    id: 70638,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "כרזה בערבית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/כרזה בערבית.docs"
  },
  {
    id: 92552,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "כרזה בעברית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/כרזה בעברית.docs"
  },
  {
    id: 65565,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדריך לתכנון מילוט במבני ציבור",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדריך לתכנון מילוט במבני ציבור.docs"
  },
  {
    id: 79011,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "עלון צונמי ערבית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון צונמי ערבית.docs"
  },
  {
    id: 86885,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "english",
    isPublish: false,
    status: "init",
    name: "עלון צונמי אנגלית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון צונמי אנגלית.docs"
  },
  {
    id: 57298,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "leaflets",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עלון צונמי עברית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עלון צונמי עברית.docs"
  },
  {
    id: 97248,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "ועדה לבחינת הנחיות במוסדות חינוך",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/ועדה לבחינת הנחיות במוסדות חינוך.docs"
  },
  {
    id: 47010,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הנחיות לאנשים עם מוגבלות - מוסדות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הנחיות לאנשים עם מוגבלות - מוסדות.docs"
  },
  {
    id: 37556,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "guides",
    language: "arabic",
    isPublish: false,
    status: "init",
    name: "היערכות אנשים עם מוגבלות ערבית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/היערכות אנשים עם מוגבלות ערבית.docs"
  },
  {
    id: 68111,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "היערכות אנשים עם מוגבלות עברית",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/היערכות אנשים עם מוגבלות עברית.docs"
  },
  {
    id: 22576,
    category: "היערכות הרשות המקומית",
    subCategory: "אתר סיוע לאוכלוסייה",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אתר סיוע לאוכלוסיה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אתר סיוע לאוכלוסיה.docs"
  },
  {
    id: 15928,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "השוואת שיטות חישוב תגובת אתר",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/השוואת שיטות חישוב תגובת אתר.docs"
  },
  {
    id: 16416,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מדידות תגובת אתר אזור גלילות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדידות תגובת אתר אזור גלילות.docs"
  },
  {
    id: 28546,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר אזור באר שבע",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר אזור באר שבע.docs"
  },
  {
    id: 30456,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר באר שבע",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר באר שבע.docs"
  },
  {
    id: 26894,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר דימונה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר דימונה.docs"
  },
  {
    id: 82139,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר שדה דב",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר שדה דב.docs"
  },
  {
    id: 51746,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר רחובות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר רחובות.docs"
  },
  {
    id: 74519,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר קרית גת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר קרית גת.docs"
  },
  {
    id: 43031,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר קריות חיפה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר קריות חיפה.docs"
  },
  {
    id: 53266,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר צור יצחק",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר צור יצחק.docs"
  },
  {
    id: 98228,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר עראבה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר עראבה.docs"
  },
  {
    id: 59734,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר עמק זבולון",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר עמק זבולון.docs"
  },
  {
    id: 87664,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר נורדיה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר נורדיה.docs"
  },
  {
    id: 47158,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר מגדל העמק",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר מגדל העמק.docs"
  },
  {
    id: 74423,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר ירוחם",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר ירוחם.docs"
  },
  {
    id: 80980,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר ומיקרוזונציה אילת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר ומיקרוזונציה אילת.docs"
  },
  {
    id: 25990,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר גלילות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר גלילות.docs"
  },
  {
    id: 61312,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר גדידה מכר",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר גדידה מכר.docs"
  },
  {
    id: 61669,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר בעיר טבריה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר בעיר טבריה.docs"
  },
  {
    id: 18079,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר אשקלון",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר אשקלון.docs"
  },
  {
    id: 86901,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מדידות תגובת אתר אזור דימונה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדידות תגובת אתר אזור דימונה.docs"
  },
  {
    id: 87745,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "תגובת אתר אכסאל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תגובת אתר אכסאל.docs"
  },
  {
    id: 71571,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אופן חישוב תגובת אתר",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אופן חישוב תגובת אתר.docs"
  },
  {
    id: 18351,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "איכון מקורות לרעידה בים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/איכון מקורות לרעידה בים.docs"
  },
  {
    id: 51099,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פיזור מוקדים בגלבוע כרמל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פיזור מוקדים בגלבוע כרמל.docs"
  },
  {
    id: 64623,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הערת מקור רעד מגלי פי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הערת מקור רעד מגלי פי.docs"
  },
  {
    id: 83427,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "כיול הרשת להערכת רעידות רחוקות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/כיול הרשת להערכת רעידות רחוקות.docs"
  },
  {
    id: 34157,
    category: "סיסמולוגיה",
    subCategory: "רעידות משנה",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "התפתחות בזמן של רעשי משנה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/התפתחות בזמן של רעשי משנה.docs"
  },
  {
    id: 67452,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מאגר אקסלוגרמות לתאוצות קרקע",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מאגר אקסלוגרמות לתאוצות קרקע.docs"
  },
  {
    id: 69867,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "מודל מהירות תלת מימדי לאיכון רעידות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מודל מהירות תלת מימדי לאיכון רעידות.docs"
  },
  {
    id: 75317,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תאוצות קרקע בתקן הבניה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תאוצות קרקע בתקן הבניה.docs"
  },
  {
    id: 42104,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "אלגוריתם להערכת תאוצות קרקע",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אלגוריתם להערכת תאוצות קרקע.docs"
  },
  {
    id: 16932,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חיזוק מבני אבן",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/חיזוק מבני אבן.docs"
  },
  {
    id: 44109,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדריך לחיזוק מבנים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדריך לחיזוק מבנים.docs"
  },
  {
    id: 25019,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "דוגמאות לחישוב לפי 413 חלק3",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/דוגמאות לחישוב לפי 413 חלק3.docs"
  },
  {
    id: 58538,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סקר רמות סיכון קביל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סקר רמות סיכון קביל.docs"
  },
  {
    id: 92454,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גישות לשדרוג סייסמי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/גישות לשדרוג סייסמי.docs"
  },
  {
    id: 57250,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עמידות מבנים עם קירות הקשחה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עמידות מבנים עם קירות הקשחה.docs"
  },
  {
    id: 72333,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עמידות עמודים עטופים ביריעות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עמידות עמודים עטופים ביריעות.docs"
  },
  {
    id: 71234,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אופטימיזציה של מבנים מבטון",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אופטימיזציה של מבנים מבטון.docs"
  },
  {
    id: 77055,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חישוב תקופה בסיסית למבנים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/חישוב תקופה בסיסית למבנים.docs"
  },
  {
    id: 79621,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חציית העתק עי צנרת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/חציית העתק עי צנרת.docs"
  },
  {
    id: 43456,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "שימוש בבידוד סייסמי במבנים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/שימוש בבידוד סייסמי במבנים.docs"
  },
  {
    id: 56246,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תכנון מבנה על העתק פעיל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תכנון מבנה על העתק פעיל.docs"
  },
  {
    id: 87790,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פרמטרים של רעידות ותכן מבנים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פרמטרים של רעידות ותכן מבנים.docs"
  },
  {
    id: 84150,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חישוב זמן מחזור מבנים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/חישוב זמן מחזור מבנים.docs"
  },
  {
    id: 92276,
    category: "הנדסה סיסמית",
    subCategory: "אלמנטים לא מבניים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "עיגון מערכות לא מבניות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/עיגון מערכות לא מבניות.docs"
  },
  {
    id: 42255,
    category: "הנדסה סיסמית",
    subCategory: "הערכת נזק למבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "זיהוי והערכת נזק בבתי חולים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/זיהוי והערכת נזק בבתי חולים.docs"
  },
  {
    id: 37338,
    category: "הנדסה סיסמית",
    subCategory: "הערכת נזק למבנים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "יצירת תמונת מצב מבני חקלאות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/יצירת תמונת מצב מבני חקלאות.docs"
  },
  {
    id: 64080,
    category: "היערכות לצונאמי",
    subCategory: "מערך \"מים אדירים\"",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מודל תומך החלטה להתרעת צונמי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מודל תומך החלטה להתרעת צונמי.docs"
  },
  {
    id: 39868,
    category: "היערכות לצונאמי",
    subCategory: "תפיסה לאומית לצונמי",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תפיסה לאומית לצונמי",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תפיסה לאומית לצונמי.docs"
  },
  {
    id: 22843,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכות התרעה מקומיות",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "פרמטרים להתרעה להפסקת פעילות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/פרמטרים להתרעה להפסקת פעילות.docs"
  },
  {
    id: 73218,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "תפיסת הציבור את תרועה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/תפיסת הציבור את תרועה.docs"
  },
  {
    id: 66336,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סקר היתכנות למערכת התרעה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סקר היתכנות למערכת התרעה.docs"
  },
  {
    id: 74535,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדיניות התרעה לרעידות אדמה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדיניות התרעה לרעידות אדמה.docs"
  },
  {
    id: 70208,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "english",
    isPublish: false,
    status: "init",
    name: "ועדה בינל להקמת מערכת התרעה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/ועדה בינל להקמת מערכת התרעה.docs"
  },
  {
    id: 73445,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "reports",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "בחינה ראשונית למערכת התרעה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/בחינה ראשונית למערכת התרעה.docs"
  },
  {
    id: 87158,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "אופטימיזציה של אלגוריתם התרעה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/אופטימיזציה של אלגוריתם התרעה.docs"
  },
  {
    id: 74130,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "נספחים מדריך היערכות אתרי מורשת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/נספחים מדריך היערכות אתרי מורשת.docs"
  },
  {
    id: 11343,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "נספחים תיק שטח אתרי מורשת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/נספחים תיק שטח אתרי מורשת.docs"
  },
  {
    id: 21774,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מדריך היערכות אתרי מורשת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מדריך היערכות אתרי מורשת.docs"
  },
  {
    id: 78076,
    category: "שיקום ארוך טווח",
    subCategory: "שיקום ארוך טווח",
    mediaType: "plans",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "דוח שיקום ארוך טווח",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/דוח שיקום ארוך טווח.docs"
  },
  {
    id: 10109,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סגנון תקשורת סיכונים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סגנון תקשורת סיכונים.docs"
  },
  {
    id: 84234,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "סקר תפיסות האוכלוסיה על רעד",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/סקר תפיסות האוכלוסיה על רעד.docs"
  },
  {
    id: 77601,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הגדרת צורכי אוכלוסיות פגיעות אחרי רעידה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הגדרת צורכי אוכלוסיות פגיעות אחרי רעידה.docs"
  },
  {
    id: 88352,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מוכנות אוכלוסיית החרדים לרעידה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מוכנות אוכלוסיית החרדים לרעידה.docs"
  },
  {
    id: 12972,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר ניסויים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מחקר בתי ספר ניסויים.docs"
  },
  {
    id: 79084,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר מערך",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מחקר בתי ספר מערך.docs"
  },
  {
    id: 83491,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר חוברת לתלמיד",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מחקר בתי ספר חוברת לתלמיד.docs"
  },
  {
    id: 37831,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "מחקר בתי ספר השוואה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/מחקר בתי ספר השוואה.docs"
  },
  {
    id: 20816,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "התנהגות אוכלוסיה עם מוגבלות",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/התנהגות אוכלוסיה עם מוגבלות.docs"
  },
  {
    id: 48441,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    mediaType: "guides",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הנחיות בפישוט לשוני",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הנחיות בפישוט לשוני.docs"
  },
  {
    id: 90158,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "english",
    isPublish: false,
    status: "init",
    name: "הערכת נזק כלכלי באילת",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הערכת נזק כלכלי באילת.docs"
  },
  {
    id: 41871,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "הערכת נזקים מאקרו כלכליים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/הערכת נזקים מאקרו כלכליים.docs"
  },
  {
    id: 38075,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חוסן תעשיית האירוח בישראל",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/חוסן תעשיית האירוח בישראל.docs"
  },
  {
    id: 76408,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "היערכות לרעד בעסקים קטנים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/היערכות לרעד בעסקים קטנים.docs"
  },
  {
    id: 41185,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים משפטיים",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "המערך הרגולטורי לרעידת אדמה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/המערך הרגולטורי לרעידת אדמה.docs"
  },
  {
    id: 36865,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות המדינה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "חבילות מדיניות לחיזוק מבנים בפריפריה",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/חבילות מדיניות לחיזוק מבנים בפריפריה.docs"
  },
  {
    id: 57314,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות המדינה",
    mediaType: "studies",
    language: "hebrew",
    isPublish: false,
    status: "init",
    name: "גישות בהליך זיהוי אלמונים",
    type: "docs",
    fileUrl: "s3://s3-content-earthquake-dev/גישות בהליך זיהוי אלמונים.docs"
  }
];