@baseUrl = http://127.0.0.1:3080

### OpenAPI document
GET {{baseUrl}}/openapi.json

### Swagger UI
GET {{baseUrl}}/api-docs

### Health check
GET {{baseUrl}}/health

### Get all Elasticsearch document ids
GET {{baseUrl}}/documents/ids

### Get Elasticsearch document by id
GET {{baseUrl}}/documents/10000

### Get all Elasticsearch documents
GET {{baseUrl}}/documents

### Load initial Elasticsearch data
GET {{baseUrl}}/loadInitInfo

### Queue initial summarize Lambda jobs
GET {{baseUrl}}/loadInitSummerize
