/* eslint-disable max-lines */

import { FileItem } from "./types/data";

export const files: FileItem[] = [
  {
    id: 71381,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "העתק אור עקיבא",
    pdfUrl: "s3://earthquake-reports/העתק אור עקיבא.pdf"
  },
  {
    id: 49732,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מיפוי העתקים בברניקי",
    pdfUrl: "s3://earthquake-reports/מיפוי העתקים בברניקי.pdf"
  },
  {
    id: 84050,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עדכון מעמד העתקים 2018",
    pdfUrl: "s3://earthquake-reports/עדכון מעמד העתקים 2018.pdf"
  },
  {
    id: 71043,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עדכון מעמד העתקים 2022",
    pdfUrl: "s3://earthquake-reports/עדכון מעמד העתקים 2022.pdf"
  },
  {
    id: 28924,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "פעילות טקטונית כרמל ונשר",
    pdfUrl: "s3://earthquake-reports/פעילות טקטונית כרמל ונשר.pdf"
  },
  {
    id: 85806,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "רכס חוסם צפוני בכרמל",
    pdfUrl: "s3://earthquake-reports/רכס חוסם צפוני בכרמל.pdf"
  },
  {
    id: 84518,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "קריעת פני שטח בטבריה",
    pdfUrl: "s3://earthquake-reports/קריעת פני שטח בטבריה.pdf"
  },
  {
    id: 43221,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "העתק אחיהוד",
    pdfUrl: "s3://earthquake-reports/העתק אחיהוד.pdf"
  },
  {
    id: 54062,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מיקום העתק הכרמל מניתוח תתקרקע",
    pdfUrl: "s3://earthquake-reports/מיקום העתק הכרמל מניתוח תתקרקע.pdf"
  },
  {
    id: 20531,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "מדידות רעש לאיתור העתק הכרמל",
    pdfUrl: "s3://earthquake-reports/מדידות רעש לאיתור העתק הכרמל.pdf"
  },
  {
    id: 28385,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מפת סיכון ארצית להעתקה פעילה",
    pdfUrl: "s3://earthquake-reports/מפת סיכון ארצית להעתקה פעילה.pdf"
  },
  {
    id: 86975,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "העתקים פעילים אילת",
    pdfUrl: "s3://earthquake-reports/העתקים פעילים אילת.pdf"
  },
  {
    id: 43725,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מבנה תלת מימדי למפרץ אילת",
    pdfUrl: "s3://earthquake-reports/מבנה תלת מימדי למפרץ אילת.pdf"
  },
  {
    id: 51378,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "זמני חזרה של רעידות בכנרת",
    pdfUrl: "s3://earthquake-reports/זמני חזרה של רעידות בכנרת.pdf"
  },
  {
    id: 28515,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "העתקים במדרון היבשת וטקטוניקת מלח",
    pdfUrl: "s3://earthquake-reports/העתקים במדרון היבשת וטקטוניקת מלח.pdf"
  },
  {
    id: 33624,
    category: "גיאולוגיה",
    subCategory: "העתקים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אפיון העתקים במדרון היבשת",
    pdfUrl: "s3://earthquake-reports/אפיון העתקים במדרון היבשת.pdf"
  },
  {
    id: 44497,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הגברת תנודות בעמק זבולון א",
    pdfUrl: "s3://earthquake-reports/הגברת תנודות בעמק זבולון א.pdf"
  },
  {
    id: 73230,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הגברת תנודות בשפלה",
    pdfUrl: "s3://earthquake-reports/הגברת תנודות בשפלה.pdf"
  },
  {
    id: 38837,
    category: "גיאולוגיה",
    subCategory: "הגברת חריגה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הגברת תנודות בעמק זבולון ב",
    pdfUrl: "s3://earthquake-reports/הגברת תנודות בעמק זבולון ב.pdf"
  },
  {
    id: 44504,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "היחס בין שטח וגודל גלישות",
    pdfUrl: "s3://earthquake-reports/היחס בין שטח וגודל גלישות.pdf"
  },
  {
    id: 47412,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "גלישות אזור אילת אילות",
    pdfUrl: "s3://earthquake-reports/גלישות אזור אילת אילות.pdf"
  },
  {
    id: 63280,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "גלישות באזור בית שאן",
    pdfUrl: "s3://earthquake-reports/גלישות באזור בית שאן.pdf"
  },
  {
    id: 93247,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סיכון נפילת סלעים חפציבה",
    pdfUrl: "s3://earthquake-reports/סיכון נפילת סלעים חפציבה.pdf"
  },
  {
    id: 47576,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "טיפוסי כשל מדרון בחיפה",
    pdfUrl: "s3://earthquake-reports/טיפוסי כשל מדרון בחיפה.pdf"
  },
  {
    id: 71124,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מפת סכנה ארצית לגלישות צפון",
    pdfUrl: "s3://earthquake-reports/מפת סכנה ארצית לגלישות צפון.pdf"
  },
  {
    id: 60785,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מפת סכנה ארצית לגלישות דרום",
    pdfUrl: "s3://earthquake-reports/מפת סכנה ארצית לגלישות דרום.pdf"
  },
  {
    id: 18944,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "גלישות תת ימיות במדרון היבשת",
    pdfUrl: "s3://earthquake-reports/גלישות תת ימיות במדרון היבשת.pdf"
  },
  {
    id: 30862,
    category: "גיאולוגיה",
    subCategory: "גלישת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אלגוריתם לחיזוי גלישת קרקע",
    pdfUrl: "s3://earthquake-reports/אלגוריתם לחיזוי גלישת קרקע.pdf"
  },
  {
    id: 77482,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "התנזלות בבית שאן",
    pdfUrl: "s3://earthquake-reports/התנזלות בבית שאן.pdf"
  },
  {
    id: 32438,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "התנזלות בעמק זבולון",
    pdfUrl: "s3://earthquake-reports/התנזלות בעמק זבולון.pdf"
  },
  {
    id: 15452,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "התנזלות אילת אילות",
    pdfUrl: "s3://earthquake-reports/התנזלות אילת אילות.pdf"
  },
  {
    id: 29079,
    category: "גיאולוגיה",
    subCategory: "התנזלות קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הערכה גיאוטכנית להתנזלות בזבולון",
    pdfUrl: "s3://earthquake-reports/הערכה גיאוטכנית להתנזלות בזבולון.pdf"
  },
  {
    id: 47840,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "הערכת מיקום ועוצמה מלווינים",
    pdfUrl: "s3://earthquake-reports/הערכת מיקום ועוצמה מלווינים.pdf"
  },
  {
    id: 34429,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "שאלון עדכני לקביעת עוצמות סייסמיות",
    pdfUrl: "s3://earthquake-reports/שאלון עדכני לקביעת עוצמות סייסמיות.pdf"
  },
  {
    id: 30047,
    category: "גיאולוגיה",
    subCategory: "עוצמת רעידה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אימוץ סולם עוצמה אירופאי",
    pdfUrl: "s3://earthquake-reports/אימוץ סולם עוצמה אירופאי.pdf"
  },
  {
    id: 87285,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "סימולציה לצונמי בים המלח",
    pdfUrl: "s3://earthquake-reports/סימולציה לצונמי בים המלח.pdf"
  },
  {
    id: 64444,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "מודל סיכון לצונמי בת גלים ואילת",
    pdfUrl: "s3://earthquake-reports/מודל סיכון לצונמי בת גלים ואילת.pdf"
  },
  {
    id: 57478,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הדמיית תרחישי צונמי",
    pdfUrl: "s3://earthquake-reports/הדמיית תרחישי צונמי.pdf"
  },
  {
    id: 71996,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סף מגניטודה לצונמי",
    pdfUrl: "s3://earthquake-reports/סף מגניטודה לצונמי.pdf"
  },
  {
    id: 71977,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "פגיעת צונמי בתשתיות ימיות",
    pdfUrl: "s3://earthquake-reports/פגיעת צונמי בתשתיות ימיות.pdf"
  },
  {
    id: 17214,
    category: "גיאולוגיה",
    subCategory: "סיכון לצונמי",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "ניתוח היסטורי סכנה לצונמי",
    pdfUrl: "s3://earthquake-reports/ניתוח היסטורי סכנה לצונמי.pdf"
  },
  {
    id: 30476,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סיכום סיכונים בחיפה",
    pdfUrl: "s3://earthquake-reports/סיכום סיכונים בחיפה.pdf"
  },
  {
    id: 31251,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סיכונים והעתקים בבקעת הירדן",
    pdfUrl: "s3://earthquake-reports/סיכונים והעתקים בבקעת הירדן.pdf"
  },
  {
    id: 52391,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מיפוי סיכונים אזור מתלול צורים",
    pdfUrl: "s3://earthquake-reports/מיפוי סיכונים אזור מתלול צורים.pdf"
  },
  {
    id: 79389,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "בסיס נתונים גאודטי עבור הדרום",
    pdfUrl: "s3://earthquake-reports/בסיס נתונים גאודטי עבור הדרום.pdf"
  },
  {
    id: 66857,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מיפוי סיכונים והעתקים בבית שאן",
    pdfUrl: "s3://earthquake-reports/מיפוי סיכונים והעתקים בבית שאן.pdf"
  },
  {
    id: 46514,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "הסיכון לרעידת אדמה בטבריה",
    pdfUrl: "s3://earthquake-reports/הסיכון לרעידת אדמה בטבריה.pdf"
  },
  {
    id: 13579,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "תכנת ורוניק",
    pdfUrl: "s3://earthquake-reports/תכנת ורוניק.pdf"
  },
  {
    id: 68266,
    category: "גיאולוגיה",
    subCategory: "סיכונים סייסמיים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "אפיון תופעות סביבה מרעידות",
    pdfUrl: "s3://earthquake-reports/אפיון תופעות סביבה מרעידות.pdf"
  },
  {
    id: 44293,
    category: "ועדת ההיגוי",
    subCategory: "תוכניות ותפיסות לאומיות",
    informationType: "תוכניות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "תפיסה לאומית לרעידת אדמה",
    pdfUrl: "s3://earthquake-reports/תפיסה לאומית לרעידת אדמה.pdf"
  },
  {
    id: 51490,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "פוסטר הנחיות במשטרה",
    pdfUrl: "s3://earthquake-reports/פוסטר הנחיות במשטרה.pdf"
  },
  {
    id: 14328,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "פוסטר הנחיות בבתי חולים",
    pdfUrl: "s3://earthquake-reports/פוסטר הנחיות בבתי חולים.pdf"
  },
  {
    id: 41626,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "russian",
    isPublish: false,
    status: "init",
    fileName: "עלון היערכות לרעידות אדמה רוסית",
    pdfUrl: "s3://earthquake-reports/עלון היערכות לרעידות אדמה רוסית.pdf"
  },
  {
    id: 49563,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "arabic",
    isPublish: false,
    status: "init",
    fileName: "עלון היערכות לרעידות אדמה ערבית",
    pdfUrl: "s3://earthquake-reports/עלון היערכות לרעידות אדמה ערבית.pdf"
  },
  {
    id: 52536,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "עלון היערכות לרעידות אדמה אנגלית",
    pdfUrl: "s3://earthquake-reports/עלון היערכות לרעידות אדמה אנגלית.pdf"
  },
  {
    id: 45444,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עלון היערכות לרעידות אדמה עברית",
    pdfUrl: "s3://earthquake-reports/עלון היערכות לרעידות אדמה עברית.pdf"
  },
  {
    id: 80743,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הנחיות ברעידת אדמה עברית",
    pdfUrl: "s3://earthquake-reports/הנחיות ברעידת אדמה עברית.pdf"
  },
  {
    id: 71214,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "arabic",
    isPublish: false,
    status: "init",
    fileName: "הנחיות ברעידת אדמה ערבית",
    pdfUrl: "s3://earthquake-reports/הנחיות ברעידת אדמה ערבית.pdf"
  },
  {
    id: 53736,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "russian",
    isPublish: false,
    status: "init",
    fileName: "הנחיות ברעידת אדמה רוסית",
    pdfUrl: "s3://earthquake-reports/הנחיות ברעידת אדמה רוסית.pdf"
  },
  {
    id: 29684,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "הנחיות ברעידת אדמה אנגלית",
    pdfUrl: "s3://earthquake-reports/הנחיות ברעידת אדמה אנגלית.pdf"
  },
  {
    id: 75622,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מצגת הסברה",
    pdfUrl: "s3://earthquake-reports/מצגת הסברה.pdf"
  },
  {
    id: 70638,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "arabic",
    isPublish: false,
    status: "init",
    fileName: "כרזה בערבית",
    pdfUrl: "s3://earthquake-reports/כרזה בערבית.pdf"
  },
  {
    id: 92552,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "כרזה בעברית",
    pdfUrl: "s3://earthquake-reports/כרזה בעברית.pdf"
  },
  {
    id: 65565,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מדריך לתכנון מילוט במבני ציבור",
    pdfUrl: "s3://earthquake-reports/מדריך לתכנון מילוט במבני ציבור.pdf"
  },
  {
    id: 79011,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "arabic",
    isPublish: false,
    status: "init",
    fileName: "עלון צונמי ערבית",
    pdfUrl: "s3://earthquake-reports/עלון צונמי ערבית.pdf"
  },
  {
    id: 86885,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "עלון צונמי אנגלית",
    pdfUrl: "s3://earthquake-reports/עלון צונמי אנגלית.pdf"
  },
  {
    id: 57298,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "עלוני הסברה",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עלון צונמי עברית",
    pdfUrl: "s3://earthquake-reports/עלון צונמי עברית.pdf"
  },
  {
    id: 97248,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "דוחות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "ועדה לבחינת הנחיות במוסדות חינוך",
    pdfUrl: "s3://earthquake-reports/ועדה לבחינת הנחיות במוסדות חינוך.pdf"
  },
  {
    id: 47010,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "דוחות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הנחיות לאנשים עם מוגבלות - מוסדות",
    pdfUrl: "s3://earthquake-reports/הנחיות לאנשים עם מוגבלות - מוסדות.pdf"
  },
  {
    id: 37556,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "מדריכים",
    language: "arabic",
    isPublish: false,
    status: "init",
    fileName: "היערכות אנשים עם מוגבלות ערבית",
    pdfUrl: "s3://earthquake-reports/היערכות אנשים עם מוגבלות ערבית.pdf"
  },
  {
    id: 68111,
    category: "ועדת ההיגוי",
    subCategory: "הנחיות ברעידת אדמה",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "היערכות אנשים עם מוגבלות עברית",
    pdfUrl: "s3://earthquake-reports/היערכות אנשים עם מוגבלות עברית.pdf"
  },
  {
    id: 22576,
    category: "היערכות הרשות המקומית",
    subCategory: "אתר סיוע לאוכלוסייה",
    informationType: "תוכניות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אתר סיוע לאוכלוסיה",
    pdfUrl: "s3://earthquake-reports/אתר סיוע לאוכלוסיה.pdf"
  },
  {
    id: 15928,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "השוואת שיטות חישוב תגובת אתר",
    pdfUrl: "s3://earthquake-reports/השוואת שיטות חישוב תגובת אתר.pdf"
  },
  {
    id: 16416,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "מדידות תגובת אתר אזור גלילות",
    pdfUrl: "s3://earthquake-reports/מדידות תגובת אתר אזור גלילות.pdf"
  },
  {
    id: 28546,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר אזור באר שבע",
    pdfUrl: "s3://earthquake-reports/תגובת אתר אזור באר שבע.pdf"
  },
  {
    id: 30456,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר באר שבע",
    pdfUrl: "s3://earthquake-reports/תגובת אתר באר שבע.pdf"
  },
  {
    id: 26894,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר דימונה",
    pdfUrl: "s3://earthquake-reports/תגובת אתר דימונה.pdf"
  },
  {
    id: 82139,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר שדה דב",
    pdfUrl: "s3://earthquake-reports/תגובת אתר שדה דב.pdf"
  },
  {
    id: 51746,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר רחובות",
    pdfUrl: "s3://earthquake-reports/תגובת אתר רחובות.pdf"
  },
  {
    id: 74519,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר קרית גת",
    pdfUrl: "s3://earthquake-reports/תגובת אתר קרית גת.pdf"
  },
  {
    id: 43031,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר קריות חיפה",
    pdfUrl: "s3://earthquake-reports/תגובת אתר קריות חיפה.pdf"
  },
  {
    id: 53266,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר צור יצחק",
    pdfUrl: "s3://earthquake-reports/תגובת אתר צור יצחק.pdf"
  },
  {
    id: 98228,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר עראבה",
    pdfUrl: "s3://earthquake-reports/תגובת אתר עראבה.pdf"
  },
  {
    id: 59734,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר עמק זבולון",
    pdfUrl: "s3://earthquake-reports/תגובת אתר עמק זבולון.pdf"
  },
  {
    id: 87664,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר נורדיה",
    pdfUrl: "s3://earthquake-reports/תגובת אתר נורדיה.pdf"
  },
  {
    id: 47158,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר מגדל העמק",
    pdfUrl: "s3://earthquake-reports/תגובת אתר מגדל העמק.pdf"
  },
  {
    id: 74423,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר ירוחם",
    pdfUrl: "s3://earthquake-reports/תגובת אתר ירוחם.pdf"
  },
  {
    id: 80980,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר ומיקרוזונציה אילת",
    pdfUrl: "s3://earthquake-reports/תגובת אתר ומיקרוזונציה אילת.pdf"
  },
  {
    id: 25990,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר גלילות",
    pdfUrl: "s3://earthquake-reports/תגובת אתר גלילות.pdf"
  },
  {
    id: 61312,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר גדידה מכר",
    pdfUrl: "s3://earthquake-reports/תגובת אתר גדידה מכר.pdf"
  },
  {
    id: 61669,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר בעיר טבריה",
    pdfUrl: "s3://earthquake-reports/תגובת אתר בעיר טבריה.pdf"
  },
  {
    id: 18079,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר אשקלון",
    pdfUrl: "s3://earthquake-reports/תגובת אתר אשקלון.pdf"
  },
  {
    id: 86901,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "מדידות תגובת אתר אזור דימונה",
    pdfUrl: "s3://earthquake-reports/מדידות תגובת אתר אזור דימונה.pdf"
  },
  {
    id: 87745,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "תגובת אתר אכסאל",
    pdfUrl: "s3://earthquake-reports/תגובת אתר אכסאל.pdf"
  },
  {
    id: 71571,
    category: "סיסמולוגיה",
    subCategory: "תגובת אתר",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אופן חישוב תגובת אתר",
    pdfUrl: "s3://earthquake-reports/אופן חישוב תגובת אתר.pdf"
  },
  {
    id: 18351,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "איכון מקורות לרעידה בים",
    pdfUrl: "s3://earthquake-reports/איכון מקורות לרעידה בים.pdf"
  },
  {
    id: 51099,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "פיזור מוקדים בגלבוע כרמל",
    pdfUrl: "s3://earthquake-reports/פיזור מוקדים בגלבוע כרמל.pdf"
  },
  {
    id: 64623,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "הערת מקור רעד מגלי פי",
    pdfUrl: "s3://earthquake-reports/הערת מקור רעד מגלי פי.pdf"
  },
  {
    id: 83427,
    category: "סיסמולוגיה",
    subCategory: "מוקד רע\"ד",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "כיול הרשת להערכת רעידות רחוקות",
    pdfUrl: "s3://earthquake-reports/כיול הרשת להערכת רעידות רחוקות.pdf"
  },
  {
    id: 34157,
    category: "סיסמולוגיה",
    subCategory: "רעידות משנה",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "התפתחות בזמן של רעשי משנה",
    pdfUrl: "s3://earthquake-reports/התפתחות בזמן של רעשי משנה.pdf"
  },
  {
    id: 67452,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מאגר אקסלוגרמות לתאוצות קרקע",
    pdfUrl: "s3://earthquake-reports/מאגר אקסלוגרמות לתאוצות קרקע.pdf"
  },
  {
    id: 69867,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "מודל מהירות תלת מימדי לאיכון רעידות",
    pdfUrl: "s3://earthquake-reports/מודל מהירות תלת מימדי לאיכון רעידות.pdf"
  },
  {
    id: 75317,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "תאוצות קרקע בתקן הבניה",
    pdfUrl: "s3://earthquake-reports/תאוצות קרקע בתקן הבניה.pdf"
  },
  {
    id: 42104,
    category: "סיסמולוגיה",
    subCategory: "תאוצת קרקע",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "אלגוריתם להערכת תאוצות קרקע",
    pdfUrl: "s3://earthquake-reports/אלגוריתם להערכת תאוצות קרקע.pdf"
  },
  {
    id: 16932,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "חיזוק מבני אבן",
    pdfUrl: "s3://earthquake-reports/חיזוק מבני אבן.pdf"
  },
  {
    id: 44109,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מדריך לחיזוק מבנים",
    pdfUrl: "s3://earthquake-reports/מדריך לחיזוק מבנים.pdf"
  },
  {
    id: 25019,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "דוגמאות לחישוב לפי 413 חלק3",
    pdfUrl: "s3://earthquake-reports/דוגמאות לחישוב לפי 413 חלק3.pdf"
  },
  {
    id: 58538,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סקר רמות סיכון קביל",
    pdfUrl: "s3://earthquake-reports/סקר רמות סיכון קביל.pdf"
  },
  {
    id: 92454,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "גישות לשדרוג סייסמי",
    pdfUrl: "s3://earthquake-reports/גישות לשדרוג סייסמי.pdf"
  },
  {
    id: 57250,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עמידות מבנים עם קירות הקשחה",
    pdfUrl: "s3://earthquake-reports/עמידות מבנים עם קירות הקשחה.pdf"
  },
  {
    id: 72333,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עמידות עמודים עטופים ביריעות",
    pdfUrl: "s3://earthquake-reports/עמידות עמודים עטופים ביריעות.pdf"
  },
  {
    id: 71234,
    category: "הנדסה סיסמית",
    subCategory: "שיפור עמידות מבנים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אופטימיזציה של מבנים מבטון",
    pdfUrl: "s3://earthquake-reports/אופטימיזציה של מבנים מבטון.pdf"
  },
  {
    id: 77055,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "חישוב תקופה בסיסית למבנים",
    pdfUrl: "s3://earthquake-reports/חישוב תקופה בסיסית למבנים.pdf"
  },
  {
    id: 79621,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "חציית העתק עי צנרת",
    pdfUrl: "s3://earthquake-reports/חציית העתק עי צנרת.pdf"
  },
  {
    id: 43456,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "שימוש בבידוד סייסמי במבנים",
    pdfUrl: "s3://earthquake-reports/שימוש בבידוד סייסמי במבנים.pdf"
  },
  {
    id: 56246,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "תכנון מבנה על העתק פעיל",
    pdfUrl: "s3://earthquake-reports/תכנון מבנה על העתק פעיל.pdf"
  },
  {
    id: 87790,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "פרמטרים של רעידות ותכן מבנים",
    pdfUrl: "s3://earthquake-reports/פרמטרים של רעידות ותכן מבנים.pdf"
  },
  {
    id: 84150,
    category: "הנדסה סיסמית",
    subCategory: "תכנון אנטי סייסמי",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "חישוב זמן מחזור מבנים",
    pdfUrl: "s3://earthquake-reports/חישוב זמן מחזור מבנים.pdf"
  },
  {
    id: 92276,
    category: "הנדסה סיסמית",
    subCategory: "אלמנטים לא מבניים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "עיגון מערכות לא מבניות",
    pdfUrl: "s3://earthquake-reports/עיגון מערכות לא מבניות.pdf"
  },
  {
    id: 42255,
    category: "הנדסה סיסמית",
    subCategory: "הערכת נזק למבנים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "זיהוי והערכת נזק בבתי חולים",
    pdfUrl: "s3://earthquake-reports/זיהוי והערכת נזק בבתי חולים.pdf"
  },
  {
    id: 37338,
    category: "הנדסה סיסמית",
    subCategory: "הערכת נזק למבנים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "יצירת תמונת מצב מבני חקלאות",
    pdfUrl: "s3://earthquake-reports/יצירת תמונת מצב מבני חקלאות.pdf"
  },
  {
    id: 64080,
    category: "היערכות לצונאמי",
    subCategory: "מערך \"מים אדירים\"",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מודל תומך החלטה להתרעת צונמי",
    pdfUrl: "s3://earthquake-reports/מודל תומך החלטה להתרעת צונמי.pdf"
  },
  {
    id: 39868,
    category: "היערכות לצונאמי",
    subCategory: "תפיסה לאומית לצונמי",
    informationType: "תוכניות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "תפיסה לאומית לצונמי",
    pdfUrl: "s3://earthquake-reports/תפיסה לאומית לצונמי.pdf"
  },
  {
    id: 22843,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכות התרעה מקומיות",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "פרמטרים להתרעה להפסקת פעילות",
    pdfUrl: "s3://earthquake-reports/פרמטרים להתרעה להפסקת פעילות.pdf"
  },
  {
    id: 73218,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "תפיסת הציבור את תרועה",
    pdfUrl: "s3://earthquake-reports/תפיסת הציבור את תרועה.pdf"
  },
  {
    id: 66336,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    informationType: "דוחות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סקר היתכנות למערכת התרעה",
    pdfUrl: "s3://earthquake-reports/סקר היתכנות למערכת התרעה.pdf"
  },
  {
    id: 74535,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    informationType: "דוחות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מדיניות התרעה לרעידות אדמה",
    pdfUrl: "s3://earthquake-reports/מדיניות התרעה לרעידות אדמה.pdf"
  },
  {
    id: 70208,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    informationType: "דוחות",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "ועדה בינל להקמת מערכת התרעה",
    pdfUrl: "s3://earthquake-reports/ועדה בינל להקמת מערכת התרעה.pdf"
  },
  {
    id: 73445,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    informationType: "דוחות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "בחינה ראשונית למערכת התרעה",
    pdfUrl: "s3://earthquake-reports/בחינה ראשונית למערכת התרעה.pdf"
  },
  {
    id: 87158,
    category: "התרעה לרעידת אדמה",
    subCategory: "מערכת \"תרועה\"",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "אופטימיזציה של אלגוריתם התרעה",
    pdfUrl: "s3://earthquake-reports/אופטימיזציה של אלגוריתם התרעה.pdf"
  },
  {
    id: 74130,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "נספחים מדריך היערכות אתרי מורשת",
    pdfUrl: "s3://earthquake-reports/נספחים מדריך היערכות אתרי מורשת.pdf"
  },
  {
    id: 11343,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "נספחים תיק שטח אתרי מורשת",
    pdfUrl: "s3://earthquake-reports/נספחים תיק שטח אתרי מורשת.pdf"
  },
  {
    id: 21774,
    category: "היערכות אתרי מורשת",
    subCategory: "סיכונים באתרי מורשת",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מדריך היערכות אתרי מורשת",
    pdfUrl: "s3://earthquake-reports/מדריך היערכות אתרי מורשת.pdf"
  },
  {
    id: 78076,
    category: "שיקום ארוך טווח",
    subCategory: "שיקום ארוך טווח",
    informationType: "תוכניות",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "דוח שיקום ארוך טווח",
    pdfUrl: "s3://earthquake-reports/דוח שיקום ארוך טווח.pdf"
  },
  {
    id: 10109,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סגנון תקשורת סיכונים",
    pdfUrl: "s3://earthquake-reports/סגנון תקשורת סיכונים.pdf"
  },
  {
    id: 84234,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "סקר תפיסות האוכלוסיה על רעד",
    pdfUrl: "s3://earthquake-reports/סקר תפיסות האוכלוסיה על רעד.pdf"
  },
  {
    id: 77601,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות הציבור",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "הגדרת צורכי אוכלוסיות פגיעות אחרי רעידה",
    pdfUrl: "s3://earthquake-reports/הגדרת צורכי אוכלוסיות פגיעות אחרי רעידה.pdf"
  },
  {
    id: 88352,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מוכנות אוכלוסיית החרדים לרעידה",
    pdfUrl: "s3://earthquake-reports/מוכנות אוכלוסיית החרדים לרעידה.pdf"
  },
  {
    id: 12972,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מחקר בתי ספר ניסויים",
    pdfUrl: "s3://earthquake-reports/מחקר בתי ספר ניסויים.pdf"
  },
  {
    id: 79084,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מחקר בתי ספר מערך",
    pdfUrl: "s3://earthquake-reports/מחקר בתי ספר מערך.pdf"
  },
  {
    id: 83491,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מחקר בתי ספר חוברת לתלמיד",
    pdfUrl: "s3://earthquake-reports/מחקר בתי ספר חוברת לתלמיד.pdf"
  },
  {
    id: 37831,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "מחקר בתי ספר השוואה",
    pdfUrl: "s3://earthquake-reports/מחקר בתי ספר השוואה.pdf"
  },
  {
    id: 20816,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "התנהגות אוכלוסיה עם מוגבלות",
    pdfUrl: "s3://earthquake-reports/התנהגות אוכלוסיה עם מוגבלות.pdf"
  },
  {
    id: 48441,
    category: "היבטים חברתיים כלכליים",
    subCategory: "אוכלוסיות ומגזרים",
    informationType: "מדריכים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הנחיות בפישוט לשוני",
    pdfUrl: "s3://earthquake-reports/הנחיות בפישוט לשוני.pdf"
  },
  {
    id: 90158,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    informationType: "מחקרים",
    language: "english",
    isPublish: false,
    status: "init",
    fileName: "הערכת נזק כלכלי באילת",
    pdfUrl: "s3://earthquake-reports/הערכת נזק כלכלי באילת.pdf"
  },
  {
    id: 41871,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "הערכת נזקים מאקרו כלכליים",
    pdfUrl: "s3://earthquake-reports/הערכת נזקים מאקרו כלכליים.pdf"
  },
  {
    id: 38075,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "חוסן תעשיית האירוח בישראל",
    pdfUrl: "s3://earthquake-reports/חוסן תעשיית האירוח בישראל.pdf"
  },
  {
    id: 76408,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים כלכליים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "היערכות לרעד בעסקים קטנים",
    pdfUrl: "s3://earthquake-reports/היערכות לרעד בעסקים קטנים.pdf"
  },
  {
    id: 41185,
    category: "היבטים חברתיים כלכליים",
    subCategory: "היבטים משפטיים",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "המערך הרגולטורי לרעידת אדמה",
    pdfUrl: "s3://earthquake-reports/המערך הרגולטורי לרעידת אדמה.pdf"
  },
  {
    id: 36865,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות המדינה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "חבילות מדיניות לחיזוק מבנים בפריפריה",
    pdfUrl: "s3://earthquake-reports/חבילות מדיניות לחיזוק מבנים בפריפריה.pdf"
  },
  {
    id: 57314,
    category: "היבטים חברתיים כלכליים",
    subCategory: "מוכנות המדינה",
    informationType: "מחקרים",
    language: "hebrew",
    isPublish: false,
    status: "init",
    fileName: "גישות בהליך זיהוי אלמונים",
    pdfUrl: "s3://earthquake-reports/גישות בהליך זיהוי אלמונים.pdf"
  }
];